version: '3.8'

services:
 fluree:
    image: fluree/server:d5eb31b1c2be560a92a30176dc8b0e01973859ea
    container_name: fluree
    volumes:
      - fluree_data:/opt/fluree-server/data
    networks:
      - fluree
    labels:
      - 'traefik.enable=false'


volumes:
  fluree_data:
    name: fluree-data-${ENVIRONMENT}

networks:
  fluree:
    internal: true
    name: fluree-${ENVIRONMENT}