name: transform UML model
on:
  push:
    branches:
      - "**"
    paths:
      - "models/implementation/xmi_conceptual_model/mwb_CM.xml"

jobs:
  linkML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: get model2owl
        run: |
          git clone --branch feature/linkml  https://github.com/meaningfy-ws/model2owl.git
          pwd

      - name: get-saxon
        run: pwd && cd model2owl && make get-saxon

      - name: linkML transform step
        run: |

          echo "-------------------linkML transform---------------------------------"
          sed -i "s/test\/ePO-default-config/..\/models\/implementation\/model2owl-config/g" model2owl/config-proxy.xsl
          cat model2owl/config-proxy.xsl


          CM_FILE_NAME=mwb_CM.xml
          CM_FILE_PATH=$(echo "models/implementation/xmi_conceptual_model/${CM_FILE_NAME}")
          OUTPUT_PATH_LINKML=$(echo "models/implementation/linkML/")

          ls -la models/implementation/xmi_conceptual_model/
          echo "CM_FILE_PATH is $CM_FILE_PATH"
          echo "OUTPUT_PATH_LINKML is $OUTPUT_PATH_LINKML"


          cd model2owl
          ls -la
          echo "+++++++++++++++++transform to linkML ++++++++++++++++++++++++++++"
          make linkML XMI_INPUT_FILE_PATH=../$CM_FILE_PATH OUTPUT_FOLDER_PATH=../$OUTPUT_PATH_LINKML
          echo "-------------------end transform---------------------------------"


          sed -i "s/..\/implementation\/${implementation}\/model2owl-config/test\/ePO-default-config/g" config-proxy.xsl
          cd ..

        shell: bash

      - name: remove unnecessary files
        run: |
          sudo rm -rf model2owl
        shell: bash

      - name: commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git pull
          git status

          git add .
          if [ -z "$(git status --porcelain)" ]; then
          echo "::set-output name=push::false"
          else
          git commit -m "Adding linkML files"
          echo "::set-output name=push::true"
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}